/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import type { ActionItemsRead, ActionItemsWrite } from '../models/ActionItemsModel';
import type { IGetOptions, IGetAllOptions } from '../models/CommonModels';
import type { IOperationResult } from '@microsoft/power-apps/data';
import { dataSourcesInfo } from '../../.power/schemas/appschemas/dataSourcesInfo';
import { getClient } from '@microsoft/power-apps/data';


export class ActionItemsService {
  private static readonly dataSourceName = 'actionitems';

  private static readonly client = getClient(dataSourcesInfo);

  public static async create(record: Omit<ActionItemsWrite, 'ID'>): Promise<IOperationResult<ActionItemsRead>> {
    const result = await ActionItemsService.client.createRecordAsync<Omit<ActionItemsWrite, 'ID'>, ActionItemsRead>(
      ActionItemsService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<ActionItemsWrite, 'ID'>>): Promise<IOperationResult<ActionItemsRead>> {
    const result = await ActionItemsService.client.updateRecordAsync<Partial<Omit<ActionItemsWrite, 'ID'>>, ActionItemsRead>(
      ActionItemsService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await ActionItemsService.client.deleteRecordAsync(
      ActionItemsService.dataSourceName,
      id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<ActionItemsRead>> {
    const result = await ActionItemsService.client.retrieveRecordAsync<ActionItemsRead>(
      ActionItemsService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<ActionItemsRead[]>> {
    const result = await ActionItemsService.client.retrieveMultipleRecordsAsync<ActionItemsRead>(
      ActionItemsService.dataSourceName,
      options
    );
    return result;
  }
/**
* Utility method to get possible values of a referenced entity by its name.
*/
  public static async getReferencedEntity(search: string, referencedEntityKeyNormalized: string): Promise<IOperationResult<unknown>> {
    const params: {search: string} = { search };
    const result = await ActionItemsService.client.executeAsync<{search: string}, unknown>(
      {
        connectorOperation: {
          tableName: ActionItemsService.dataSourceName,
          operationName: 'Get' + referencedEntityKeyNormalized,
          parameters: params
        }
      });
    return result;
  }

}
