import { RetroSessionsService } from "./RetroSessionsService";
import { RetroItemsService } from "./RetroItemsService";
import { ActionItemsService } from "./ActionItemsService";

// -------------------------------------------------------------------
// Types
// -------------------------------------------------------------------

export interface RetroSession {
  id: number;
  title: string;
  sprint: string;
  status: "Draft" | "Open" | "Closed";
  sessionDate: string;
}

export interface RetroItem {
  id: number;
  title: string;
  category: "What We Liked" | "What We Missed" | "What We Learned" | "Appreciations";
  sessionRefId: number;
  isAnonymous: boolean;
  submittedBy: string; // display string
  votes: number;
  actionItems: ActionItem[];
}

export interface ActionItem {
  id: number;
  title: string;
  retroItemRefId: number;
  sessionRefId: number;
  owner: string; // display string
  status: "Open" | "In Progress" | "Closed" | "Carried Over";
  targetSprint: string;
  carriedOverFrom: number | null;
}

export interface RetroBoardData {
  session: RetroSession;
  liked: RetroItem[];
  missed: RetroItem[];
  learned: RetroItem[];
  appreciations: RetroItem[];
}

// -------------------------------------------------------------------
// Helpers: Choice + People normalization for Code Apps connector
// -------------------------------------------------------------------

type ChoiceValue = { Value?: string } | string | null | undefined;
type PersonValue = Record<string, any>;

const choice = (v: ChoiceValue): string => {
  if (!v) return "";
  if (typeof v === "string") return v;
  return v.Value ?? "";
};

const toLower = (s: string) => (s ?? "").trim().toLowerCase();

function personToDisplayName(p: any): string {
  if (!p) return "";
  return (
    p.DisplayName ??
    p.Title ??
    p.Name ??
    p.Email ??
    (typeof p === "string" ? p : "")
  );
}

function extractCandidates(result: any): any[] {
  const data = result?.data ?? result?.result ?? result;
  if (!data) return [];

  if (Array.isArray(data?.value)) return data.value;
  if (Array.isArray(data?.results)) return data.results;
  if (Array.isArray(data)) return data;
  if (typeof data === "object") return [data];

  return [];
}

/**
 * Resolves a People value using the autogenerated Get<PeopleField> operation.
 * IMPORTANT: choose exact match by Email/UPN/Claims when possible.
 */
async function resolvePersonValue(
  search: string,
  referencedKeyNormalized: "SubmittedBy" | "Owner",
  service: { getReferencedEntity: (s: string, k: string) => Promise<any> }
): Promise<PersonValue> {
  const trimmed = (search ?? "").trim();
  if (!trimmed) return {};

  const needle = toLower(trimmed);

  try {
    const res = await service.getReferencedEntity(trimmed, referencedKeyNormalized);
    const candidates = extractCandidates(res);

    if (candidates.length > 0) {
      // Prefer exact Email/UPN match
      const exact =
        candidates.find((c: any) => toLower(c?.Email) === needle) ||
        candidates.find((c: any) => toLower(c?.UserPrincipalName) === needle) ||
        candidates.find((c: any) => (toLower(c?.Claims) || "").includes(needle));

      if (exact) return exact;

      // Otherwise, fall back to first candidate
      return candidates[0];
    }
  } catch (e) {
    console.warn(`resolvePersonValue failed for ${referencedKeyNormalized}`, e);
  }

  // last-resort fallback (many connectors accept Claims+Email)
  return {
    Claims: `i:0#.f|membership|${needle}`,
    Email: needle,
    DisplayName: needle,
  };
}

// -------------------------------------------------------------------
// Session Operations
// -------------------------------------------------------------------

export const getAllSessions = async (): Promise<RetroSession[]> => {
  try {
    const result = await RetroSessionsService.getAll({
      orderBy: ["SessionDate desc"],
    });

    return ((result.data as any[]) ?? []).map((r: any) => ({
      id: r.ID,
      title: r.Title,
      sprint: choice(r.Sprint),
      status: (choice(r.Status) as any) || "Draft",
      sessionDate: r.SessionDate,
    }));
  } catch (error) {
    console.error("SharePointService: Failed to fetch sessions.", error);
    return [];
  }
};

export const createSession = async (
  title: string,
  sprint: string,
  sessionDate: string
): Promise<void> => {
  await RetroSessionsService.create({
    Title: title,
    // Choice write often supports raw string, but object is safer in connector scenarios
    Sprint: { Value: sprint } as any,
    Status: { Value: "Draft" } as any,
    SessionDate: sessionDate,
  } as any);
};

export const updateSessionStatus = async (
  sessionId: number,
  status: "Draft" | "Open" | "Closed"
): Promise<void> => {
  await RetroSessionsService.update(sessionId.toString(), {
    Status: { Value: status } as any,
  } as any);
};

// -------------------------------------------------------------------
// Board Data
// -------------------------------------------------------------------

export const getRetroBoardData = async (
  sessionId: number
): Promise<RetroBoardData | null> => {
  try {
    const [sessionResult, itemResults, actionResults] = await Promise.all([
      RetroSessionsService.get(sessionId.toString()),
      RetroItemsService.getAll({
        filter: `SessionRefID eq ${sessionId}`,
        orderBy: ["ID asc"],
      }),
      ActionItemsService.getAll({
        filter: `SessionRefID eq ${sessionId}`,
        orderBy: ["ID asc"],
      }),
    ]);

    const s = sessionResult.data as any;
    if (!s) return null;

    const actionItems: ActionItem[] = ((actionResults.data as any[]) ?? []).map(
      (a: any) => ({
        id: a.ID,
        title: a.Title,
        retroItemRefId: a.RetroItemRefID,
        sessionRefId: a.SessionRefID,
        owner: personToDisplayName(a.Owner) || "",
        status: (choice(a.Status) as any) || "Open",
        targetSprint: choice(a.TargetSprint),
        carriedOverFrom: a.CarriedOverFrom ?? null,
      })
    );

    const retroItems: RetroItem[] = ((itemResults.data as any[]) ?? []).map(
      (item: any) => ({
        id: item.ID,
        title: item.Title,
        category: (choice(item.Category) as any) || "What We Liked",
        sessionRefId: item.SessionRefID,
        isAnonymous: !!item.IsAnonymous,
        submittedBy: personToDisplayName(item.SubmittedBy) || "Unknown",
        votes: item.Votes ?? 0,
        actionItems: actionItems.filter((a) => a.retroItemRefId === item.ID),
      })
    );

    return {
      session: {
        id: s.ID,
        title: s.Title,
        sprint: choice(s.Sprint),
        status: (choice(s.Status) as any) || "Draft",
        sessionDate: s.SessionDate,
      },
      liked: retroItems.filter((i) => i.category === "What We Liked"),
      missed: retroItems.filter((i) => i.category === "What We Missed"),
      learned: retroItems.filter((i) => i.category === "What We Learned"),
      appreciations: retroItems.filter((i) => i.category === "Appreciations"),
    };
  } catch (error) {
    console.error("SharePointService: Failed to fetch board data.", error);
    return null;
  }
};

// -------------------------------------------------------------------
// Retro Item Operations
// -------------------------------------------------------------------

export const addRetroItem = async (
  sessionId: number,
  category: string,
  content: string,
  isAnonymous: boolean,
  submittedBy: string // MUST be UPN/email from AuthProvider (userPrincipalName) [1](https://epmpoint-my.sharepoint.com/personal/ranjith_neela_epmpoint_com/Documents/Microsoft%20Copilot%20Chat%20Files/AuthProvider.tsx)
): Promise<void> => {
  const submittedByPerson = await resolvePersonValue(
    submittedBy,
    "SubmittedBy",
    RetroItemsService as any
  );

  await RetroItemsService.create({
    Title: content,
    Category: { Value: category } as any, // ✅ Choice write
    SessionRefID: sessionId,
    IsAnonymous: isAnonymous,
    SubmittedBy: submittedByPerson, // ✅ People write
    Votes: 0,
  } as any);
};

export const voteOnItem = async (
  itemId: number,
  nextVotes: number
): Promise<void> => {
  await RetroItemsService.update(itemId.toString(), {
    Votes: nextVotes,
  } as any);
};

// -------------------------------------------------------------------
// Action Item Operations
// -------------------------------------------------------------------

export const addActionItem = async (
  title: string,
  retroItemRefId: number,
  sessionRefId: number,
  owner: string, // should be UPN/email
  targetSprint: string
): Promise<void> => {
  const ownerPerson = await resolvePersonValue(owner, "Owner", ActionItemsService as any);

  await ActionItemsService.create({
    Title: title,
    RetroItemRefID: retroItemRefId,
    SessionRefID: sessionRefId,
    Owner: ownerPerson, // ✅ People write
    Status: { Value: "Open" } as any, // ✅ Choice write
    TargetSprint: { Value: targetSprint } as any, // ✅ Choice write (if it's a choice)
  } as any);
};

export const updateActionStatus = async (
  actionId: number,
  status: "Open" | "In Progress" | "Closed" | "Carried Over"
): Promise<void> => {
  await ActionItemsService.update(actionId.toString(), {
    Status: { Value: status } as any,
  } as any);
};

// -------------------------------------------------------------------
// Carry-Over Logic (FR-07)
// -------------------------------------------------------------------

export const carryOverActions = async (
  fromSessionId: number,
  toSessionId: number,
  toSprint: string
): Promise<void> => {
  const result = await ActionItemsService.getAll({
    filter: `SessionRefID eq ${fromSessionId} and (Status eq 'Open' or Status eq 'In Progress')`,
  });

  const incompleteActions = (result.data as any[]) ?? [];

  const carryOverPromises = incompleteActions.map((action: any) =>
    ActionItemsService.create({
      Title: action.Title,
      RetroItemRefID: action.RetroItemRefID,
      SessionRefID: toSessionId,
      Owner: action.Owner, // ✅ keep person object
      Status: { Value: "Carried Over" } as any,
      TargetSprint: { Value: toSprint } as any,
      CarriedOverFrom: action.ID,
    } as any)
  );

  await Promise.all(carryOverPromises);
};